### PR TITLE
Pass taskListActivitiesPerSecond down to ActivityWorker

### PR DESCRIPTION
**Pull request by sokada1221**
resolves https://github.com/uber/cadence-java-client/issues/555

**Test results:**
- [X] Unit tests
- [X] Local integration tests with taskListActivitiesPerSecond set to 0.5, 1 and 2
- [X] Local integration tests without taskListActivitiesPerSecond set

### CODE REVIEW

**Comment by longquanzheng** [comment]
@sokada1221 sorry we didn't approve it in time. Can you resolve the conflict? and I will merge it int. The code is moved to SingleWorkerOptions.java, should be pretty straightforward to resolve.

**Comment by sokada1221** [comment]
Sure. I'll take a look this weekend. Thanks!

**Comment by sokada1221** [comment]
@longquanzheng Conflict should be resolved now. PTAL again. Thanks!

**Review by longquanzheng — APPROVED** [review]

**Comment by longquanzheng** [comment]
The test failure will be fixed after https://github.com/uber/cadence-java-client/pull/568

**Review by meiliang86 — APPROVED** [review]

**Pull request merged**
