### PR TITLE
Added missing fields to local activity task

### PR DESCRIPTION
**Pull request by sndre**
## Summary
This PR makes local activities report the same as metadata as activities. Now `Activity.getTask().getWorkflowExecution()` and `getWorkflowDomain()` return data for local activities.

## Reviewer
@mfateev

### CODE REVIEW

**Comment by sndre** [comment]
@meiliang86, do you mind taking a look at this PR?

**Comment by sndre** [comment]
hey @meiliang86, do you have a sense when this PR will get into the next SDK release? Thank you!

**Comment by vancexu** [comment]
> hey @meiliang86, do you have a sense when this PR will get into the next SDK release? Thank you!

@sndre FYI We just released this in 2.7.3.

**Comment by sndre** [comment]
@vancexu, thank you, that was fast! 👍

**Pull request merged**
